-- =====================================================================
-- RLS smoke-test teardown — Sprint 3.6
-- =====================================================================
--
-- Sprint 3.6 status: NO-OP MARKER
-- -------------------------------
-- The Sprint B2 RLS smoke teardown DELETEs rows from the v1
-- tables (`module_bookings`, `module_progress`, `enrollments`,
-- `modules`, plus the v1 FK columns on `payments` and
-- `meeting_links`, and the v1 PK on `resource_grants`). The
-- v1 hierarchy is dropped in
-- `20260715000000_drop_v1_back_compat_tables.sql`. The
-- teardown deletes would now fail at execution time — the
-- v1 tables no longer exist.
--
-- The single source of truth for the post-Sprint-3.6 RLS
-- regression is `rls_smoke_assertions_v2.sql`. The v2 suite
-- rolls its own test data back inside a single transaction
-- (`begin … rollback`), so it does not need a separate
-- teardown script. The Sprint 3.6 commit keeps this file in
-- place so the `scripts/rls-smoke.sh` runner continues to
-- invoke it (one line in the runner); the runner is otherwise
-- unchanged. When the v1 RLS suite is needed again (Sprint
-- 5+), the teardown can be rewritten against the v2 fixtures
-- in `rls_smoke_assertions_v2.sql`.
--
-- Why the file is empty rather than deleted
-- -----------------------------------------
-- Deleting the file would require editing `scripts/rls-smoke.sh`
-- to remove the run_sql line, and would invalidate the git
-- history that explains the v1 → v2 transition. The empty
-- marker is a one-line sentinel that any future reader can
-- grep for.
-- =====================================================================

-- No-op. The v1 hierarchy is gone; the v2 suite is
-- self-contained and rolls back inside its own transaction.
select 1 as rls_smoke_v1_teardown_noop_marker;
