-- =====================================================================
-- RLS smoke-test fixture — Sprint 3.6
-- =====================================================================
--
-- Sprint 3.6 status: NO-OP MARKER
-- -------------------------------
-- The Sprint B2 RLS smoke fixture populated v1 tables
-- (`modules`, `enrollments`, `module_progress`,
-- `module_bookings`, `payments.enrollment_id`,
-- `meeting_links.module_booking_id`,
-- `resource_grants.enrollment_id`) that the v1 assertions
-- target. The v1 hierarchy is dropped in
-- `20260715000000_drop_v1_back_compat_tables.sql`. The
-- fixture rows would now fail at INSERT time — the v1
-- tables no longer exist.
--
-- The single source of truth for the post-Sprint-3.6 RLS
-- regression is `rls_smoke_assertions_v2.sql` (10 v2 policy
-- blocks, added in Sprint 3.5). The v2 suite is fully
-- self-contained: it inserts its own anonymous users and
-- per-suite fixtures, asserts, and rolls back inside the
-- same transaction. It does NOT need a separate setup
-- script. The Sprint 3.6 commit keeps this file in place
-- so the `scripts/rls-smoke.sh` runner continues to invoke
-- it (one line in the runner); the runner is otherwise
-- unchanged. When the v1 RLS suite is needed again (Sprint
-- 5+), the fixture and assertions can be rewritten against
-- the v2 fixtures in `rls_smoke_assertions_v2.sql`.
--
-- Why the file is empty rather than deleted
-- -----------------------------------------
-- Deleting the file would require editing `scripts/rls-smoke.sh`
-- to remove the run_sql line, and would invalidate the git
-- history that explains the v1 → v2 transition. The empty
-- marker is a one-line sentinel that any future reader can
-- grep for.
-- =====================================================================

-- No-op. The v1 hierarchy is gone; the v2 suite is
-- self-contained and does not need a separate setup.
select 1 as rls_smoke_v1_setup_noop_marker;
