/**
 * Stand-in for the type generated by:
 *   pnpm db:types
 * Run the command above to overwrite this file with the real
 * generated types. Until that runs, every table is permissive
 * (`Record<string, unknown>`) so the existing 21 route handlers
 * from Phase 1 keep type-checking. Services that need a stronger
 * shape cast at the boundary (`as unknown as Course`, etc.).
 *
 * Sprint A: services/courses.ts and services/tutors.ts cast
 * to their domain types because the marketing site cares about
 * specific column names. The casts are localised and well
 * documented; replacing them with the real generated types is
 * a one-liner once `pnpm db:types` has run.
 *
 * The `Relationships: []` tuple (instead of the broader
 * `GenericRelationship[]`) is required by `@supabase/postgrest-js`
 * so the select-chain type inferrer doesn't fall through to
 * `SelectQueryError<…>`, which is `never`. Once the real
 * generated types land, the Relationships array is populated by
 * Supabase CLI and the empty tuple is replaced.
 */
export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];

type AnyTable = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: [];
};

type AnyView = {
  Row: Record<string, unknown>;
};

type AnyFunction = {
  Args: Record<string, unknown>;
  Returns: unknown;
};

export type Database = {
  public: {
    Tables: {
      profiles: AnyTable;
      tutors: AnyTable;
      courses: AnyTable;
      course_tutors: AnyTable;
      bookings: AnyTable;
      payments: AnyTable;
      meeting_links: AnyTable;
      resources: AnyTable;
      resource_grants: AnyTable;
      notifications: AnyTable;
      audit_logs: AnyTable;
      subscriptions: AnyTable;
      coupons: AnyTable;
      invoices: AnyTable;
      webhook_events: AnyTable;
      n8n_executions: AnyTable;
      n8n_dead_letters: AnyTable;
    };
    Views: Record<string, AnyView>;
    Functions: Record<string, AnyFunction>;
    Enums: {
      booking_status:
        | 'pending_payment'
        | 'confirmed'
        | 'completed'
        | 'cancelled'
        | 'no_show'
        | 'rescheduled';
      payment_status: 'pending' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded';
      payment_provider: 'stripe' | 'other';
      user_role: 'student' | 'admin' | 'super_admin';
      subscription_status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete';
      coupon_kind: 'percent' | 'amount' | 'free_session';
      invoice_status: 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';
    };
    CompositeTypes: Record<string, Record<string, unknown>>;
  };
};
