/**
 * Stand-in for the type generated by:
 *   pnpm db:types
 * Run the command above to overwrite this file with the real
 * generated types. The shape mirrors `public.*` tables in the
 * Supabase schema.
 */
export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>;
    Views: Record<string, { Row: Record<string, unknown> }>;
    Functions: Record<string, { Args: Record<string, unknown>; Returns: unknown }>;
    Enums: {
      booking_status:    'pending_payment' | 'confirmed' | 'completed' | 'cancelled' | 'no_show' | 'rescheduled';
      payment_status:    'pending' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded';
      payment_provider:  'stripe' | 'other';
      user_role:         'student' | 'admin' | 'super_admin';
    };
  };
};
